In [113]:
 
import numpy as np 
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

import math
import pandas as pd 
import matplotlib.pyplot as plt

# import seaborn as sns
import sklearn.metrics as metrics
%matplotlib inline
import os
# from pandas_ml import ConfusionMatrix

In [114]:
data = pd.read_csv('CIC-IDS-2017-9.csv')
# test = pd.read_csv('UNSW_NB15_testing-set.csv')
# combined_data = pd.concat([train, test]).drop(['id'],axis=1)
combined_data = data

vector = combined_data[' Label']

In [115]:
from sklearn.preprocessing import LabelEncoder,normalize
le1 = LabelEncoder()
le = LabelEncoder()

vector = combined_data[' Label']
print("Label:", set(list(vector))) # use print to make it print on single line 

combined_data[' Label'] = le1.fit_transform(vector)
# combined_data['proto'] = le.fit_transform(combined_data['proto'])
# combined_data['service'] = le.fit_transform(combined_data['service'])
# combined_data['state'] = le.fit_transform(combined_data['state'])

vector = combined_data[' Label']

Label: {'BENIGN', 'Bot'}

In [116]:
y_label = combined_data.iloc[:,78].values.flatten()
dict = {}
for i in y_label:
    dict.update({i:dict.get(i,0)+1})
dict

{0: 189067, 1: 1966}

In [117]:
le1.inverse_transform([0,1])
combined_data.head(3)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0.005989,0.939505,0.000149,0.000056,0.005220,0.000008,0.016237,0.000000,0.033918,0.029041,...,0.571429,0.000003,3.124006e-07,0.000003,2.688679e-06,0.134167,0.006512,0.136667,0.128333,0
1,0.000000,0.947978,0.002616,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.088319,1.453303e-01,0.178302,1.792453e-07,0.101667,0.090546,0.173333,0.045875,0
2,0.082451,0.000834,0.000101,0.000000,0.000499,0.000000,0.001128,0.012043,0.004713,0.000000,...,0.571429,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0

In [118]:
# combined_data_reduced=combined_data.drop(['Timestamp','Flow Duration'],axis=1)
combined_data_reduced=combined_data

combined_data_reduced = combined_data_reduced.dropna(axis=0)
combined_data_reduced.replace([np.inf, -np.inf], 0)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0.005989,0.939505,0.000149,0.000056,0.005220,8.063796e-06,0.016237,0.000000,0.033918,0.029041,...,0.571429,0.000003,3.124006e-07,0.000003,2.688679e-06,0.134167,0.006512,0.136667,0.128333,0
1,0.000000,0.947978,0.002616,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.088319,1.453303e-01,0.178302,1.792453e-07,0.101667,0.090546,0.173333,0.045875,0
2,0.082451,0.000834,0.000101,0.000000,0.000499,0.000000e+00,0.001128,0.012043,0.004713,0.000000,...,0.571429,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0
3,0.000000,0.000456,0.000014,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0
4,0.001355,0.000005,0.000029,0.000014,0.000392,6.602871e-07,0.009388,0.000000,0.011639,0.015883,...,0.357143,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190999,0.000816,0.000512,0.000014,0.000007,0.000146,5.645933e-07,0.001813,0.019355,0.007575,0.000000,...,0.357143,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1
191000,0.000816,0.000002,0.000005,0.000007,0.000065,4.338118e-07,0.001612,0.017204,0.006733,0.000000,...,0.571429,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1
191001,0.000816,0.000002,0.000005,0.000007,0.000073,5.645933e-07,0.001813,0.019355,0.007575,0.000000,...,0.571429,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1
191002,0.001894,0.000140,0.000000,0.000004,0.000039,7.655502e-08,0.001934,0.020645,0.008080,0.000000,...,0.357143,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0
191003,0.000816,0.000001,0.000005,0.000007,0.000055,1.594896e-07,0.001370,0.014624,0.005723,0.000000,...,0.357143,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0

In [119]:

print(np.isnan(combined_data_reduced).any()[np.isnan(combined_data_reduced).any() == True])
print(np.isinf(combined_data_reduced).any()[np.isinf(combined_data_reduced).any() == True])

Series([], dtype: bool)
Series([], dtype: bool)

In [120]:
data_x = combined_data_reduced.drop([' Label'], axis=1) # droped label
data_y = combined_data_reduced.loc[:,[' Label']]
# del combined_data # free mem
X_train, X_test, y_train, y_test = train_test_split(data_x, data_y, test_size=.20, random_state=42) # TODO

y_train = y_train.values.flatten()
y_test = y_test.values.flatten()

In [121]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import Normalizer

In [122]:
X = X_train
T = X_test
Y = y_train
C = y_test

scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

scaler = Normalizer().fit(T)
testT = scaler.transform(T)

traindata = np.array(trainX)
trainlabel = np.array(Y)

testdata = np.array(testT)
testlabel = np.array(C)
testlabel = testlabel.flatten()

In [123]:
from sklearn.ensemble import AdaBoostClassifier
from imblearn.ensemble import EasyEnsembleClassifier
from imblearn.ensemble import BalancedBaggingClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
from imblearn.ensemble import RUSBoostClassifier

In [124]:
np.savetxt("EXP.txt", testlabel)

In [125]:
# EE = EasyEnsembleClassifier(n_estimators=10, n_jobs=1,
#              replacement=False, sampling_strategy='auto',verbose=0, warm_start=False,
#                                      base_estimator=DecisionTreeClassifier())
# EE.fit(traindata, trainlabel)
# predicted4 = EE.predict(testdata)
# np.savetxt("EE.txt", predicted4) 
# # cm4 = ConfusionMatrix(expected, predicted4)
# # cm4.stats()

In [126]:
# BB = BalancedBaggingClassifier(n_estimators=10, random_state=42)
# BB.fit(traindata, trainlabel)
# predicted5 = BB.predict(testdata)
# np.savetxt("BB.txt", predicted5)

In [127]:
# RUSB = RUSBoostClassifier(random_state=42)
# RUSB.fit(X_train, y_train)
# BB.fit(traindata, trainlabel)
# predicted6 = RUSB.predict(testdata)
# np.savetxt("RUSB.txt", predicted6)

In [128]:
AB = AdaBoostClassifier(n_estimators=1,random_state=42,learning_rate=1)
AB.fit(X_train, y_train)
AB.fit(traindata, trainlabel)
predicted7 = AB.predict(testdata)
np.savetxt("AB.txt", predicted7)

In [17]:
from imblearn.over_sampling import SMOTE
smote_enn = SMOTE(random_state=42)
X_resampled, y_resampled = smote_enn.fit_resample(data_x, data_y)

data_x3 = np.append(data_x, X_resampled, axis = 0)
data_y3 = np.append(data_y.values, y_resampled)

In [18]:
# from imblearn.combine import SMOTETomek
# smote_tomek = SMOTETomek(random_state=0)
# X_resampled2, y_resampled2 = smote_tomek.fit_resample(data_x, data_y)

# data_x4 = np.append(data_x, X_resampled2, axis = 0)
# data_y4 = np.append(data_y.values, y_resampled2)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(data_x3, data_y3, test_size=.20, random_state=42) # TODO

In [20]:
Y_train = data_y.values.flatten()
dict = {}
for i in Y_train:
    dict.update({i:dict.get(i,0)+1})
dict

{0: 188946, 1: 1964}

In [21]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape) # test is larger... good 
print(y_test.shape)

(455041, 78)
(455041,)
(113761, 78)
(113761,)

In [22]:
X = X_train
T = X_test
Y = y_train
C = y_test

scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

scaler = Normalizer().fit(T)
testT = scaler.transform(T)

traindata = np.array(trainX)
trainlabel = np.array(Y)

testdata = np.array(testT)
testlabel = np.array(C)
testlabel = testlabel.flatten()

In [23]:

KNN = KNeighborsClassifier()
KNN.fit(traindata, trainlabel)

DT = DecisionTreeClassifier()
DT.fit(traindata, trainlabel)

RF = RandomForestClassifier(n_estimators=100)
RF.fit(traindata, trainlabel)

RandomForestClassifier()

In [ ]:
expected2 = testlabel
np.savetxt("EXP2.txt", expected2) 
predicted1 =  KNN.predict(testdata)
np.savetxt("KNN.txt", predicted1)
predicted2 =  DT.predict(testdata)
np.savetxt("DT.txt", predicted2) 
predicted3 = RF.predict(testdata)
np.savetxt("RF.txt", predicted3)