In [2]:
import argparse
import pandas as pd
import numpy as np
from preprocess import preprocess
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_recall_curve, precision_score, recall_score, average_precision_score, roc_curve, auc, confusion_matrix, mean_squared_error,classification_report
import time

import matplotlib.pyplot as plt
from keras.utils import to_categorical

trainset = pd.read_csv('./data/NSL-KDD/KDDTrain+.txt', sep=",", header=None)
testset = pd.read_csv('./data/NSL-KDD/KDDTest+.txt', sep=",", header=None)

#下面部分是GAN训练并且生成数据
processor = preprocess()
print("数据预处理....")
df_train, df_test, train_Normal, train_R2L, train_U2R, train_Dos, train_Probe,test_Normal, test_R2L, test_U2R, test_Dos, test_Probe,train_Attack,test_Attack = processor.create_df(df_train=trainset, df_test=testset)
# normal_df, R2L_df, R2L_df_train, R2L_df_test = processor.create_df(df_train=trainset, df_test=testset)
print("已完成数据预处理")

Using TensorFlow backend.

数据预处理....
已完成数据预处理

In [3]:
dt={'Dos':pd.Series([len(train_Dos),len(test_Dos)],index=['Train','Test']),
   'Probe':pd.Series([len(train_Probe),len(test_Probe)],index=['Train','Test']),
   'R2L':pd.Series([len(train_R2L),len(test_R2L)],index=['Train','Test']),
   'U2R':pd.Series([len(train_U2R),len(test_U2R)],index=['Train','Test']),
   'Normal':pd.Series([len(train_Normal),len(test_Normal)],index=['Train','Test']),
   'Total_attack':pd.Series([len(train_Attack),len(test_Attack)],index=['Train','Test']),
   'Total':pd.Series([len(df_train),len(df_test)],index=['Train','Test'])}
type_df=pd.DataFrame(dt)
cols = ['Dos','Probe','R2L','U2R','Normal','Total_attack','Total']
type_df = type_df[cols]
display(type_df)

         Dos  Probe   R2L  U2R  Normal  Total_attack   Total
Train  11656  45927   995   52   67343         58630  125973
Test    2421   7460  2885   67    9711         12833   22544

In [4]:
#加入生成数据的R2L类别二分类
generated_data = pd.read_csv('./output2/fake_examples.csv', sep=",", header=None)
generated_data = processor.gererated_preprocess(generated_data)
generated_data.head(3)

,Duration,Protocol_type,Service,Flag,Src_bytes,Dst_bytes,Land,Wrong_fragment,Urgent,Hot,...,Dst_host_srv_count,Dst_host_same_srv_rate,Dst_host_diff_srv_rate,Dst_host_same_src_port_rate,Dst_host_srv_diff_host_rate,Dst_host_serror_rate,Dst_host_srv_serror_rate,Dst_host_rerror_rate,Dst_host_srv_rerror_rate,attack_type
0,0.023381,0.337760,0.543059,0.632417,0.060709,0.061058,0.061155,0.060931,0.061090,0.061215,...,0.136977,0.095528,0.103247,0.044616,0.103006,0.999941,1.000000,0.039759,0.975339,1
1,0.019404,0.428382,0.607096,0.675547,0.066396,0.066913,0.066426,0.065931,0.065706,0.068302,...,0.067395,0.706444,0.082226,0.990614,0.121055,0.092070,0.211256,0.225578,0.367397,1
2,0.017988,0.353297,0.622369,0.625998,0.058701,0.059895,0.061084,0.056650,0.055695,0.087155,...,-0.278023,0.999893,0.311403,0.823468,-0.762270,1.000000,-0.859975,0.999911,0.994451,1

In [5]:


#train_add_BiR2L = train_Normal.append(generated_data)

#train_add_BiR2L = processor.merge_df(df_train, generated_data)
#train_add_BiR2L = np.concatenate(df_train, generated_data)

train_BiR2L = train_Normal.append(train_R2L)
train_add_BiR2L = train_BiR2L.append(generated_data)
X_train_add_R2L,y_train_add_R2L = processor.split_df(train_add_BiR2L)

test_BiR2L = test_Normal.append(test_R2L)
X_test_R2L,y_test_R2L = processor.split_df(test_BiR2L)

X_train_add_R2L.shape

(73338, 41)

In [6]:
#全局二分类
df_train2 = df_train.append(generated_data)
X_train_Bi,y_train_Bi = processor.split_df(df_train2)
y_train_Bi = y_train_Bi.replace(4,1).replace(3,1).replace(2,1)

X_test_Bi,y_test_Bi = processor.split_df(df_test)
y_test_Bi = y_test_Bi.replace(4,1).replace(3,1).replace(2,1)

In [7]:
#Dos类二分类
train_BiDos = train_Normal.append(train_Dos)
X_train_Dos,y_train_Dos = processor.split_df(train_BiDos)
y_train_Dos = y_train_Dos.replace(2,1)

test_BiDos = test_Normal.append(test_Dos)
X_test_Dos,y_test_Dos = processor.split_df(test_BiDos)
y_test_Dos = y_test_Dos.replace(2,1)

In [8]:
#R2L类二分类
#train_BiR2L = train_Normal.append(train_R2L)
X_train_R2L,y_train_R2L = processor.split_df(train_BiR2L)


# test_BiR2L = test_Normal.append(test_R2L)
# X_test_R2L,y_test_R2L = processor.split_df(test_BiR2L)
X_train_R2L.shape

(68338, 41)

In [9]:
#U2R类二分类
train_BiU2R = train_Normal.append(train_U2R)
X_train_U2R,y_train_U2R = processor.split_df(train_BiU2R)
y_train_U2R = y_train_U2R.replace(4,1)

test_BiU2R = test_Normal.append(test_U2R)
X_test_U2R,y_test_U2R = processor.split_df(test_BiU2R)
y_test_U2R = y_test_U2R.replace(4,1)

In [10]:
#Probe类二分类
train_BiProbe = train_Normal.append(train_Probe)
X_train_Probe,y_train_Probe = processor.split_df(train_BiProbe)
y_train_Probe = y_train_Probe.replace(3,1)

test_BiProbe = test_Normal.append(test_Probe)
X_test_Probe,y_test_Probe = processor.split_df(test_BiProbe)
y_test_Probe = y_test_Probe.replace(3,1)

In [11]:
# X = X_train_add_R2L
# Y = y_train_add_R2L
# C = y_test_R2L
# T = X_test_R2L

X = X_train_Bi
Y = y_train_Bi
C = y_test_Bi
T = X_test_Bi

In [12]:
Y = Y.astype(int)

In [13]:
import numpy as np
import pandas as pd
from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import Normalizer
from pandas_ml import ConfusionMatrix
# traindata = pd.read_csv('UNSW_NB15_training-set.csv', header=None)
# testdata = pd.read_csv('UNSW_NB15_testing-set.csv', header=None)
# traindata = pd.read_csv('kddtrain.csv', header=None)
# testdata = pd.read_csv('kddtest.csv', header=None)


# X = traindata.iloc[:,1:42]
# Y = traindata.iloc[:,0]
# C = testdata.iloc[:,0]
# T = testdata.iloc[:,1:42]


scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

scaler = Normalizer().fit(T)
testT = scaler.transform(T)


traindata = np.array(trainX)
trainlabel = np.array(Y)

testdata = np.array(testT)
testlabel = np.array(C)


model = LogisticRegression()
model.fit(traindata, trainlabel)


# make predictions
expected = testlabel
predicted = model.predict(testdata)

#predicted = predicted.reshape(len(predicted),1)
print(expected.shape)
print(predicted.shape)

print("***************************************************************")

D:\Anaconda3\envs\TF_36a\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

(22544,)
(22544,)
***************************************************************

In [14]:
model = LogisticRegression()
model.fit(traindata, trainlabel)
print(model)

# make predictions
expected = testlabel
predicted = model.predict(testdata)

#predicted = predicted.reshape(len(predicted),1)
print(expected.shape)
print(predicted.shape)


cm = ConfusionMatrix(expected, predicted)

expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()

np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')

print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()
print("***************************************************************")

D:\Anaconda3\envs\TF_36a\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)
(22544,)
(22544,)
population: 22544
P: 12833
N: 9711
PositiveTest: 8677
NegativeTest: 13867
TP: 8030
TN: 9064
FP: 647
FN: 4803
TPR: 0.625730538456
TNR: 0.933374523736
PPV: 0.9254350582
NPV: 0.653638133699
FPR: 0.066625476264
FDR: 0.0745649418002
FNR: 0.374269461544
ACC: 0.758250532292
F1_score: 0.746629474663
MCC: 0.569001540393
informedness: 0.559105062192
markedness: 0.579073191899
prevalence: 0.569242370476
LRP: 9.39176083299
LRN: 0.400985297998
DOR: 23.4217086758
FOR: 0.346361866301
Predicted  False  True  __all__
Actual
False       9064   647     9711
True        4803  8030    12833
__all__    13867  8677    22544
(22544,)
(22544,)
***************************************************************

In [15]:
# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(traindata, trainlabel)
print(model)
# make predictions
expected = testlabel
predicted = model.predict(testdata)

#expected = expected.flatten()
#predicted = predicted.reshape(len(predicted),1)
print(expected.shape)
print(predicted.shape)

cm = ConfusionMatrix(expected, predicted)

expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()

np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')

print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()
print("***************************************************************")



# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(traindata, trainlabel)
print(model)
# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model

#expected = expected.flatten()
print(expected.shape)
print(predicted.shape)

cm = ConfusionMatrix(expected, predicted)
expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()
np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')
print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()


# cm = metrics.confusion_matrix(expected, predicted)
# print(cm)
# tpr = float(cm[0][0])/np.sum(cm[0])
# fpr = float(cm[1][1])/np.sum(cm[1])
# print("%.3f" %tpr)
# print("%.3f" %fpr)
# print("Accuracy")
# print("%.3f" %ACC)
# print("precision")
# print("%.3f" %precision)
# print("recall")
# print("%.3f" %recall)
# print("f-score")
# print("%.3f" %f1)
# print("fpr")
# print("%.3f" %fpr)
# print("tpr")
# print("%.3f" %tpr)
print("***************************************************************")



model = DecisionTreeClassifier()
model.fit(traindata, trainlabel)
print(model)
# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model

#expected = expected.flatten()

cm = ConfusionMatrix(expected, predicted)
expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()
np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')
print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()
print("***************************************************************")

print("AdaBoostClassifier")
model = AdaBoostClassifier(n_estimators=100)
model.fit(traindata, trainlabel)

# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model

#expected = expected.flatten()

cm = ConfusionMatrix(expected, predicted)
expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()
np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')
print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()

print("***************************************************************")



print("RandomForestClassifier")
model = RandomForestClassifier(n_estimators=100)
model = model.fit(traindata, trainlabel)

# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model
#expected = expected.flatten()

cm = ConfusionMatrix(expected, predicted)
expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()
np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')
print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()

print("end****end***********************************************************")

GaussianNB(priors=None, var_smoothing=1e-09)
(22544,)
(22544,)
population: 22544
P: 12833
N: 9711
PositiveTest: 12686
NegativeTest: 9858
TP: 8092
TN: 5117
FP: 4594
FN: 4741
TPR: 0.630561832775
TNR: 0.526928225723
PPV: 0.637868516475
NPV: 0.519070805437
FPR: 0.473071774277
FDR: 0.362131483525
FNR: 0.369438167225
ACC: 0.585920865862
F1_score: 0.634194129864
MCC: 0.157214449045
informedness: 0.157490058498
markedness: 0.156939321912
prevalence: 0.569242370476
LRP: 1.33290943798
LRN: 0.701116678117
DOR: 1.90112356414
FOR: 0.480929194563
Predicted  False   True  __all__
Actual
False       5117   4594     9711
True        4741   8092    12833
__all__     9858  12686    22544
(22544,)
(22544,)
***************************************************************
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')
(22544,)
(22544,)
population: 22544
P: 12833
N: 9711
PositiveTest: 8217
NegativeTest: 14327
TP: 7993
TN: 9487
FP: 224
FN: 4840
TPR: 0.622847346684
TNR: 0.976933374524
PPV: 0.972739442619
NPV: 0.662176310463
FPR: 0.0230666254763
FDR: 0.027260557381
FNR: 0.377152653316
ACC: 0.775372604684
F1_score: 0.759429928741
MCC: 0.617098232285
informedness: 0.599780721208
markedness: 0.634915753082
prevalence: 0.569242370476
LRP: 27.0021008199
LRN: 0.386057701734
DOR: 69.9431735168
FOR: 0.337823689537
Predicted  False  True  __all__
Actual
False       9487   224     9711
True        4840  7993    12833
__all__    14327  8217    22544
(22544,)
(22544,)
***************************************************************
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
population: 22544
P: 12833
N: 9711
PositiveTest: 8869
NegativeTest: 13675
TP: 8594
TN: 9436
FP: 275
FN: 4239
TPR: 0.669679731941
TNR: 0.971681598188
PPV: 0.968993122111
NPV: 0.690018281536
FPR: 0.0283184018124
FDR: 0.0310068778893
FNR: 0.330320268059
ACC: 0.799769339957
F1_score: 0.792000737259
MCC: 0.650126472629
informedness: 0.641361330129
markedness: 0.659011403646
prevalence: 0.569242370476
LRP: 23.6482177341
LRN: 0.339947024493
DOR: 69.5644204251
FOR: 0.309981718464
Predicted  False  True  __all__
Actual
False       9436   275     9711
True        4239  8594    12833
__all__    13675  8869    22544
(22544,)
(22544,)
***************************************************************
AdaBoostClassifier
population: 22544
P: 12833
N: 9711
PositiveTest: 9186
NegativeTest: 13358
TP: 8477
TN: 9002
FP: 709
FN: 4356
TPR: 0.660562612016
TNR: 0.926990011327
PPV: 0.922817330721
NPV: 0.673903278934
FPR: 0.0730099886726
FDR: 0.0771826692793
FNR: 0.339437387984
ACC: 0.775328246984
F1_score: 0.769971388346
MCC: 0.592118872867
informedness: 0.587552623343
markedness: 0.596720609655
prevalence: 0.569242370476
LRP: 9.04756491578
LRN: 0.366171570175
DOR: 24.7085400744
FOR: 0.326096721066
Predicted  False  True  __all__
Actual
False       9002   709     9711
True        4356  8477    12833
__all__    13358  9186    22544
(22544,)
(22544,)
***************************************************************
RandomForestClassifier
population: 22544
P: 12833
N: 9711
PositiveTest: 7992
NegativeTest: 14552
TP: 7728
TN: 9447
FP: 264
FN: 5105
TPR: 0.602197459674
TNR: 0.97281433426
PPV: 0.966966966967
NPV: 0.649189114898
FPR: 0.0271856657399
FDR: 0.033033033033
FNR: 0.397802540326
ACC: 0.761843506033
F1_score: 0.74218487395
MCC: 0.595228539283
informedness: 0.575011793934
markedness: 0.616156081865
prevalence: 0.569242370476
LRP: 22.1512861019
LRN: 0.408919283275
DOR: 54.1703143086
FOR: 0.350810885102
Predicted  False  True  __all__
Actual
False       9447   264     9711
True        5105  7728    12833
__all__    14552  7992    22544
(22544,)
(22544,)
end****end***********************************************************

In [16]:
model = svm.SVC(kernel='linear')#调参
model = model.fit(traindata, trainlabel)

# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model
expected = expected.flatten()
print(expected.shape)
print(predicted.shape)

cm = ConfusionMatrix(expected, predicted)
expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()
np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')
print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()

print("***************************************************************")

(22544,)
(22544,)
population: 22544
P: 12833
N: 9711
PositiveTest: 7878
NegativeTest: 14666
TP: 7612
TN: 9445
FP: 266
FN: 5221
TPR: 0.593158263851
TNR: 0.972608382247
PPV: 0.966235085047
NPV: 0.644006545752
FPR: 0.0273916177531
FDR: 0.033764914953
FNR: 0.406841736149
ACC: 0.756609297374
F1_score: 0.735068321182
MCC: 0.587583492592
informedness: 0.565766646098
markedness: 0.610241630799
prevalence: 0.569242370476
LRP: 21.6547364671
LRN: 0.418299639994
DOR: 51.768479809
FOR: 0.355993454248
Predicted  False  True  __all__
Actual
False       9445   266     9711
True        5221  7612    12833
__all__    14666  7878    22544
(22544,)
(22544,)
***************************************************************

In [17]:
from keras.models import Sequential, Model
from keras.layers import Dense, Dropout, Activation, Embedding
from keras.wrappers.scikit_learn import KerasClassifier
import h5py
from keras import callbacks
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
from keras.utils import to_categorical
def build_model():
    # 1. define the network
    model = Sequential()
    #model = Model()
    model.add(Dense(1024,input_dim=41,activation='relu'))  
    model.add(Dropout(0.01))
    model.add(Dense(1))
    model.add(Activation('sigmoid'))
    # try using different optimizers and different optimizer configs
    model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])   
   # model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])   
    return model

In [18]:
#DNN
checkpointer = callbacks.ModelCheckpoint(filepath="./DNNResult/checkpoint-{epoch:02d}.hdf5", verbose=1, save_best_only=True, monitor='loss')
#csv_logger = CSVLogger('./DNNResult/training_set_dnnanalysis.csv',separator=',', append=False)
model = KerasClassifier(build_fn=build_model, epochs=100, batch_size=84)
#model.fit(traindata, trainlabel, callbacks=[checkpointer,csv_logger])
model.fit(traindata, trainlabel, callbacks=[checkpointer])
#model.save("DNNResult/dnn1layer_model.hdf5")

# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model
expected = expected.flatten()
predicted = predicted.flatten()
print(predicted.shape)
print(expected.shape)

cm = ConfusionMatrix(expected, predicted)
expected = np.array(expected)
predicted = np.array(predicted)
cm.print_stats()
np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')
print(cm)
print(expected.shape)
print(predicted.shape)
cm.stats()

print("***************************************************************")

Epoch 1/100
130973/130973 [==============================] - 6s 50us/step - loss: 0.0898 - acc: 0.9690

Epoch 00001: loss improved from inf to 0.08976, saving model to ./DNNResult/checkpoint-01.hdf5
Epoch 2/100
130973/130973 [==============================] - 5s 37us/step - loss: 0.0463 - acc: 0.9832

Epoch 00002: loss improved from 0.08976 to 0.04630, saving model to ./DNNResult/checkpoint-02.hdf5
Epoch 3/100
130973/130973 [==============================] - 5s 42us/step - loss: 0.0346 - acc: 0.9882

Epoch 00003: loss improved from 0.04630 to 0.03463, saving model to ./DNNResult/checkpoint-03.hdf5
Epoch 4/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0279 - acc: 0.9902

Epoch 00004: loss improved from 0.03463 to 0.02789, saving model to ./DNNResult/checkpoint-04.hdf5
Epoch 5/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0238 - acc: 0.9919

Epoch 00005: loss improved from 0.02789 to 0.02378, saving model to ./DNNResult/checkpoint-05.hdf5
Epoch 6/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0210 - acc: 0.9929

Epoch 00006: loss improved from 0.02378 to 0.02097, saving model to ./DNNResult/checkpoint-06.hdf5
Epoch 7/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0189 - acc: 0.9937

Epoch 00007: loss improved from 0.02097 to 0.01886, saving model to ./DNNResult/checkpoint-07.hdf5
Epoch 8/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0174 - acc: 0.9942

Epoch 00008: loss improved from 0.01886 to 0.01737, saving model to ./DNNResult/checkpoint-08.hdf5
Epoch 9/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0163 - acc: 0.9946

Epoch 00009: loss improved from 0.01737 to 0.01626, saving model to ./DNNResult/checkpoint-09.hdf5
Epoch 10/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0153 - acc: 0.9946

Epoch 00010: loss improved from 0.01626 to 0.01530, saving model to ./DNNResult/checkpoint-10.hdf5
Epoch 11/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0146 - acc: 0.9950

Epoch 00011: loss improved from 0.01530 to 0.01456, saving model to ./DNNResult/checkpoint-11.hdf5
Epoch 12/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0142 - acc: 0.9952

Epoch 00012: loss improved from 0.01456 to 0.01419, saving model to ./DNNResult/checkpoint-12.hdf5
Epoch 13/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0135 - acc: 0.9954

Epoch 00013: loss improved from 0.01419 to 0.01347, saving model to ./DNNResult/checkpoint-13.hdf5
Epoch 14/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0132 - acc: 0.9955

Epoch 00014: loss improved from 0.01347 to 0.01322, saving model to ./DNNResult/checkpoint-14.hdf5
Epoch 15/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0125 - acc: 0.9955

Epoch 00015: loss improved from 0.01322 to 0.01251, saving model to ./DNNResult/checkpoint-15.hdf5
Epoch 16/100
130973/130973 [==============================] - 6s 42us/step - loss: 0.0122 - acc: 0.9958

Epoch 00016: loss improved from 0.01251 to 0.01220, saving model to ./DNNResult/checkpoint-16.hdf5
Epoch 17/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0119 - acc: 0.9958

Epoch 00017: loss improved from 0.01220 to 0.01188, saving model to ./DNNResult/checkpoint-17.hdf5
Epoch 18/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0116 - acc: 0.9959

Epoch 00018: loss improved from 0.01188 to 0.01159, saving model to ./DNNResult/checkpoint-18.hdf5
Epoch 19/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0113 - acc: 0.9960

Epoch 00019: loss improved from 0.01159 to 0.01129, saving model to ./DNNResult/checkpoint-19.hdf5
Epoch 20/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0110 - acc: 0.9963

Epoch 00020: loss improved from 0.01129 to 0.01097, saving model to ./DNNResult/checkpoint-20.hdf5
Epoch 21/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0109 - acc: 0.9961

Epoch 00021: loss improved from 0.01097 to 0.01086, saving model to ./DNNResult/checkpoint-21.hdf5
Epoch 22/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0106 - acc: 0.9961

Epoch 00022: loss improved from 0.01086 to 0.01065, saving model to ./DNNResult/checkpoint-22.hdf5
Epoch 23/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0103 - acc: 0.9962

Epoch 00023: loss improved from 0.01065 to 0.01031, saving model to ./DNNResult/checkpoint-23.hdf5
Epoch 24/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0101 - acc: 0.9964

Epoch 00024: loss improved from 0.01031 to 0.01012, saving model to ./DNNResult/checkpoint-24.hdf5
Epoch 25/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0098 - acc: 0.9964

Epoch 00025: loss improved from 0.01012 to 0.00978, saving model to ./DNNResult/checkpoint-25.hdf5
Epoch 26/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0096 - acc: 0.9964

Epoch 00026: loss improved from 0.00978 to 0.00965, saving model to ./DNNResult/checkpoint-26.hdf5
Epoch 27/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0095 - acc: 0.9964

Epoch 00027: loss improved from 0.00965 to 0.00948, saving model to ./DNNResult/checkpoint-27.hdf5
Epoch 28/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0096 - acc: 0.9966

Epoch 00028: loss did not improve from 0.00948
Epoch 29/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0094 - acc: 0.9966

Epoch 00029: loss improved from 0.00948 to 0.00935, saving model to ./DNNResult/checkpoint-29.hdf5
Epoch 30/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0091 - acc: 0.9966

Epoch 00030: loss improved from 0.00935 to 0.00915, saving model to ./DNNResult/checkpoint-30.hdf5
Epoch 31/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0091 - acc: 0.9967

Epoch 00031: loss improved from 0.00915 to 0.00914, saving model to ./DNNResult/checkpoint-31.hdf5
Epoch 32/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0090 - acc: 0.9968

Epoch 00032: loss improved from 0.00914 to 0.00899, saving model to ./DNNResult/checkpoint-32.hdf5
Epoch 33/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0088 - acc: 0.9967

Epoch 00033: loss improved from 0.00899 to 0.00882, saving model to ./DNNResult/checkpoint-33.hdf5
Epoch 34/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0087 - acc: 0.9968

Epoch 00034: loss improved from 0.00882 to 0.00865, saving model to ./DNNResult/checkpoint-34.hdf5
Epoch 35/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0084 - acc: 0.9969

Epoch 00035: loss improved from 0.00865 to 0.00845, saving model to ./DNNResult/checkpoint-35.hdf5
Epoch 36/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0086 - acc: 0.9967

Epoch 00036: loss did not improve from 0.00845
Epoch 37/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0086 - acc: 0.9968

Epoch 00037: loss did not improve from 0.00845
Epoch 38/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0081 - acc: 0.9968

Epoch 00038: loss improved from 0.00845 to 0.00814, saving model to ./DNNResult/checkpoint-38.hdf5
Epoch 39/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0081 - acc: 0.9971

Epoch 00039: loss improved from 0.00814 to 0.00813, saving model to ./DNNResult/checkpoint-39.hdf5
Epoch 40/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0081 - acc: 0.9970

Epoch 00040: loss improved from 0.00813 to 0.00808, saving model to ./DNNResult/checkpoint-40.hdf5
Epoch 41/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0081 - acc: 0.9971

Epoch 00041: loss improved from 0.00808 to 0.00806, saving model to ./DNNResult/checkpoint-41.hdf5
Epoch 42/100

130973/130973 [==============================] - 5s 39us/step - loss: 0.0080 - acc: 0.9971

Epoch 00042: loss improved from 0.00806 to 0.00797, saving model to ./DNNResult/checkpoint-42.hdf5
Epoch 43/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0078 - acc: 0.9971

Epoch 00043: loss improved from 0.00797 to 0.00778, saving model to ./DNNResult/checkpoint-43.hdf5
Epoch 44/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0078 - acc: 0.9971

Epoch 00044: loss improved from 0.00778 to 0.00778, saving model to ./DNNResult/checkpoint-44.hdf5
Epoch 45/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0079 - acc: 0.9970

Epoch 00045: loss did not improve from 0.00778
Epoch 46/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0078 - acc: 0.9972

Epoch 00046: loss improved from 0.00778 to 0.00776, saving model to ./DNNResult/checkpoint-46.hdf5
Epoch 47/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0077 - acc: 0.9972

Epoch 00047: loss improved from 0.00776 to 0.00770, saving model to ./DNNResult/checkpoint-47.hdf5
Epoch 48/100
130973/130973 [==============================] - 5s 42us/step - loss: 0.0078 - acc: 0.9972

Epoch 00048: loss did not improve from 0.00770
Epoch 49/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0074 - acc: 0.9973

Epoch 00049: loss improved from 0.00770 to 0.00744, saving model to ./DNNResult/checkpoint-49.hdf5
Epoch 50/100
130973/130973 [==============================] - ETA: 0s - loss: 0.0077 - acc: 0.997 - 5s 39us/step - loss: 0.0077 - acc: 0.9971

Epoch 00050: loss did not improve from 0.00744
Epoch 51/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0075 - acc: 0.9972

Epoch 00051: loss did not improve from 0.00744
Epoch 52/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0073 - acc: 0.9973

Epoch 00052: loss improved from 0.00744 to 0.00734, saving model to ./DNNResult/checkpoint-52.hdf5
Epoch 53/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0073 - acc: 0.9973

Epoch 00053: loss did not improve from 0.00734
Epoch 54/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0073 - acc: 0.9974

Epoch 00054: loss improved from 0.00734 to 0.00727, saving model to ./DNNResult/checkpoint-54.hdf5
Epoch 55/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0072 - acc: 0.9974

Epoch 00055: loss improved from 0.00727 to 0.00718, saving model to ./DNNResult/checkpoint-55.hdf5
Epoch 56/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0070 - acc: 0.9973

Epoch 00056: loss improved from 0.00718 to 0.00704, saving model to ./DNNResult/checkpoint-56.hdf5
Epoch 57/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0072 - acc: 0.9973

Epoch 00057: loss did not improve from 0.00704
Epoch 58/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0070 - acc: 0.9973

Epoch 00058: loss improved from 0.00704 to 0.00697, saving model to ./DNNResult/checkpoint-58.hdf5
Epoch 59/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0070 - acc: 0.9974

Epoch 00059: loss did not improve from 0.00697
Epoch 60/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0071 - acc: 0.9973

Epoch 00060: loss did not improve from 0.00697
Epoch 61/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0068 - acc: 0.9975

Epoch 00061: loss improved from 0.00697 to 0.00678, saving model to ./DNNResult/checkpoint-61.hdf5
Epoch 62/100
130973/130973 [==============================] - 5s 42us/step - loss: 0.0071 - acc: 0.9973

Epoch 00062: loss did not improve from 0.00678
Epoch 63/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0068 - acc: 0.9975

Epoch 00063: loss did not improve from 0.00678
Epoch 64/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0068 - acc: 0.9976

Epoch 00064: loss did not improve from 0.00678
Epoch 65/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0068 - acc: 0.9975

Epoch 00065: loss improved from 0.00678 to 0.00677, saving model to ./DNNResult/checkpoint-65.hdf5
Epoch 66/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0069 - acc: 0.9974

Epoch 00066: loss did not improve from 0.00677
Epoch 67/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0068 - acc: 0.9976

Epoch 00067: loss did not improve from 0.00677
Epoch 68/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0066 - acc: 0.9978

Epoch 00068: loss improved from 0.00677 to 0.00661, saving model to ./DNNResult/checkpoint-68.hdf5
Epoch 69/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0067 - acc: 0.9976

Epoch 00069: loss did not improve from 0.00661
Epoch 70/100
130973/130973 [==============================] - 6s 44us/step - loss: 0.0067 - acc: 0.9975

Epoch 00070: loss did not improve from 0.00661
Epoch 71/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0064 - acc: 0.9977

Epoch 00071: loss improved from 0.00661 to 0.00642, saving model to ./DNNResult/checkpoint-71.hdf5
Epoch 72/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0067 - acc: 0.9975

Epoch 00072: loss did not improve from 0.00642
Epoch 73/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0066 - acc: 0.9976

Epoch 00073: loss did not improve from 0.00642
Epoch 74/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0064 - acc: 0.9975

Epoch 00074: loss improved from 0.00642 to 0.00640, saving model to ./DNNResult/checkpoint-74.hdf5
Epoch 75/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0064 - acc: 0.9976

Epoch 00075: loss improved from 0.00640 to 0.00639, saving model to ./DNNResult/checkpoint-75.hdf5
Epoch 76/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0065 - acc: 0.9976

Epoch 00076: loss did not improve from 0.00639
Epoch 77/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0062 - acc: 0.9978

Epoch 00077: loss improved from 0.00639 to 0.00624, saving model to ./DNNResult/checkpoint-77.hdf5
Epoch 78/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0064 - acc: 0.9976

Epoch 00078: loss did not improve from 0.00624
Epoch 79/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0063 - acc: 0.9977

Epoch 00079: loss did not improve from 0.00624
Epoch 80/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0061 - acc: 0.9977

Epoch 00080: loss improved from 0.00624 to 0.00612, saving model to ./DNNResult/checkpoint-80.hdf5
Epoch 81/100
130973/130973 [==============================] - 6s 43us/step - loss: 0.0063 - acc: 0.9976

Epoch 00081: loss did not improve from 0.00612
Epoch 82/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0063 - acc: 0.9978

Epoch 00082: loss did not improve from 0.00612
Epoch 83/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0063 - acc: 0.9977

Epoch 00083: loss did not improve from 0.00612
Epoch 84/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0062 - acc: 0.9976

Epoch 00084: loss did not improve from 0.00612
Epoch 85/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0061 - acc: 0.9977

Epoch 00085: loss did not improve from 0.00612
Epoch 86/100
130973/130973 [==============================] - 5s 42us/step - loss: 0.0061 - acc: 0.9978

Epoch 00086: loss did not improve from 0.00612
Epoch 87/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0061 - acc: 0.9978

Epoch 00087: loss improved from 0.00612 to 0.00611, saving model to ./DNNResult/checkpoint-87.hdf5
Epoch 88/100
130973/130973 [==============================] - 6s 42us/step - loss: 0.0064 - acc: 0.9976

Epoch 00088: loss did not improve from 0.00611
Epoch 89/100

130973/130973 [==============================] - 6s 44us/step - loss: 0.0060 - acc: 0.9977

Epoch 00089: loss improved from 0.00611 to 0.00596, saving model to ./DNNResult/checkpoint-89.hdf5
Epoch 90/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0058 - acc: 0.9978

Epoch 00090: loss improved from 0.00596 to 0.00581, saving model to ./DNNResult/checkpoint-90.hdf5
Epoch 91/100
130973/130973 [==============================] - 5s 41us/step - loss: 0.0061 - acc: 0.9976

Epoch 00091: loss did not improve from 0.00581
Epoch 92/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0058 - acc: 0.9978

Epoch 00092: loss improved from 0.00581 to 0.00580, saving model to ./DNNResult/checkpoint-92.hdf5
Epoch 93/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0061 - acc: 0.9977

Epoch 00093: loss did not improve from 0.00580
Epoch 94/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0057 - acc: 0.9978

Epoch 00094: loss improved from 0.00580 to 0.00566, saving model to ./DNNResult/checkpoint-94.hdf5
Epoch 95/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0059 - acc: 0.9978

Epoch 00095: loss did not improve from 0.00566
Epoch 96/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0059 - acc: 0.9977

Epoch 00096: loss did not improve from 0.00566
Epoch 97/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0058 - acc: 0.9978

Epoch 00097: loss did not improve from 0.00566
Epoch 98/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0061 - acc: 0.9977

Epoch 00098: loss did not improve from 0.00566
Epoch 99/100
130973/130973 [==============================] - 5s 40us/step - loss: 0.0058 - acc: 0.9978

Epoch 00099: loss did not improve from 0.00566
Epoch 100/100
130973/130973 [==============================] - 5s 39us/step - loss: 0.0057 - acc: 0.9979

Epoch 00100: loss did not improve from 0.00566
(22544,)
(22544,)
population: 22544
P: 12833
N: 9711
PositiveTest: 9039
NegativeTest: 13505
TP: 8714
TN: 9386
FP: 325
FN: 4119
TPR: 0.679030624172
TNR: 0.966532797858
PPV: 0.96404469521
NPV: 0.695001851166
FPR: 0.0334672021419
FDR: 0.0359553047904
FNR: 0.320969375828
ACC: 0.802874378992
F1_score: 0.796817849305
MCC: 0.652270146301
informedness: 0.64556342203
markedness: 0.659046546376
prevalence: 0.569242370476
LRP: 20.2894350503
LRN: 0.332083273883
DOR: 61.0974314154
FOR: 0.304998148834
Predicted  False  True  __all__
Actual
False       9386   325     9711
True        4119  8714    12833
__all__    13505  9039    22544
(22544,)
(22544,)
***************************************************************